import atexit
import logging
import os
from typing import Any, Dict, Optional, Union

import numpy as np
import torch

from .distributed import get_machine_local_and_dist_rank


class WandbLogger:
    """WandB logger with the same interface as TensorBoardLogger.

    Only logs from rank 0 in distributed settings.

    Auth: reads WANDB_API_KEY from the environment. Never prompts (so it works
    in non-TTY job runners) and never tries to write ~/.netrc (so a full home
    filesystem doesn't kill the run). If WANDB_API_KEY is unset, falls back to
    offline mode.

    All wandb cache/run dirs are forced under `dir` (which should live on the
    cluster mount, not $HOME).
    """

    def __init__(
        self,
        project: str,
        name: Optional[str] = None,
        dir: Optional[str] = None,
        config: Optional[Dict[str, Any]] = None,
        mode: Optional[str] = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            project: WandB project name
            name: Run name (defaults to auto-generated by WandB)
            dir: Local directory for WandB run/cache files (must be writable)
            config: Optional dict of hyperparameters to log
            mode: 'online', 'offline', or 'disabled'. If None, auto-decide:
                  online when WANDB_API_KEY is set, otherwise offline.
        """
        self._run = None
        _, self._rank = get_machine_local_and_dist_rank()

        if self._rank == 0:
            if dir is not None:
                os.makedirs(dir, exist_ok=True)
                # Redirect every wandb dotfile/cache off of $HOME onto the
                # cluster mount so a full home FS can't break logging.
                os.environ.setdefault("WANDB_DIR", dir)
                os.environ.setdefault("WANDB_CACHE_DIR", os.path.join(dir, "cache"))
                os.environ.setdefault("WANDB_CONFIG_DIR", os.path.join(dir, "config"))
                os.environ.setdefault("WANDB_DATA_DIR", os.path.join(dir, "data"))

            if mode is None:
                mode = "online" if os.environ.get("WANDB_API_KEY") else "offline"
            os.environ["WANDB_MODE"] = mode

            import wandb

            self._run = wandb.init(
                project=project,
                name=name,
                dir=dir,
                config=config or {},
                mode=mode,
                **kwargs,
            )
            logging.info(
                f"WandB run initialized (mode={mode}): {getattr(self._run, 'url', '<offline>')}"
            )
        else:
            logging.debug(
                f"Not logging on this process because rank {self._rank} != 0"
            )

        atexit.register(self.close)

    def close(self) -> None:
        if self._run is not None:
            self._run.finish()
            self._run = None

    def flush(self) -> None:
        pass  # WandB syncs automatically

    def log_dict(self, payload: Dict[str, Any], step: int) -> None:
        if self._run is None:
            return
        import wandb
        wandb.log(payload, step=step)

    def log(self, name: str, data: Any, step: int) -> None:
        if self._run is None:
            return
        import wandb
        wandb.log({name: data}, step=step)

    def log_visuals(
        self,
        name: str,
        data: Union[torch.Tensor, np.ndarray],
        step: int,
        fps: int = 4,
    ) -> None:
        if self._run is None:
            return
        import wandb

        if isinstance(data, torch.Tensor):
            data = data.cpu().numpy()

        if data.ndim == 3:
            # HWC or CHW image — wandb.Image expects HWC
            if data.shape[0] in (1, 3, 4):  # likely CHW
                data = np.transpose(data, (1, 2, 0))
            wandb.log({name: wandb.Image(data)}, step=step)
        elif data.ndim == 5:
            # (B, T, C, H, W) video
            wandb.log({name: wandb.Video(data, fps=fps)}, step=step)
        else:
            raise ValueError(
                f"Unsupported data dimensions: {data.ndim}. "
                "Expected 3D for images or 5D for videos."
            )
