import atexit
import logging
from typing import Any, Dict, Optional, Union

import numpy as np
import torch

from .distributed import get_machine_local_and_dist_rank


class WandbLogger:
    """WandB logger with the same interface as TensorBoardLogger.

    Only logs from rank 0 in distributed settings.
    """

    def __init__(
        self,
        project: str,
        name: Optional[str] = None,
        dir: Optional[str] = None,
        config: Optional[Dict[str, Any]] = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            project: WandB project name
            name: Run name (defaults to auto-generated by WandB)
            dir: Local directory for WandB files
            config: Optional dict of hyperparameters to log
        """
        self._run = None
        _, self._rank = get_machine_local_and_dist_rank()

        if self._rank == 0:
            import wandb

            self._run = wandb.init(
                project=project,
                name=name,
                dir=dir,
                config=config or {},
                **kwargs,
            )
            logging.info(f"WandB run initialized: {self._run.url}")
        else:
            logging.debug(
                f"Not logging on this process because rank {self._rank} != 0"
            )

        atexit.register(self.close)

    def close(self) -> None:
        if self._run is not None:
            self._run.finish()
            self._run = None

    def flush(self) -> None:
        pass  # WandB syncs automatically

    def log_dict(self, payload: Dict[str, Any], step: int) -> None:
        if self._run is None:
            return
        import wandb
        wandb.log(payload, step=step)

    def log(self, name: str, data: Any, step: int) -> None:
        if self._run is None:
            return
        import wandb
        wandb.log({name: data}, step=step)

    def log_visuals(
        self,
        name: str,
        data: Union[torch.Tensor, np.ndarray],
        step: int,
        fps: int = 4,
    ) -> None:
        if self._run is None:
            return
        import wandb

        if isinstance(data, torch.Tensor):
            data = data.cpu().numpy()

        if data.ndim == 3:
            # HWC or CHW image — wandb.Image expects HWC
            if data.shape[0] in (1, 3, 4):  # likely CHW
                data = np.transpose(data, (1, 2, 0))
            wandb.log({name: wandb.Image(data)}, step=step)
        elif data.ndim == 5:
            # (B, T, C, H, W) video
            wandb.log({name: wandb.Video(data, fps=fps)}, step=step)
        else:
            raise ValueError(
                f"Unsupported data dimensions: {data.ndim}. "
                "Expected 3D for images or 5D for videos."
            )
